version: 1.1.{build}-{branch}

build: false

environment:
  matrix:
    - platform: x86

    - platform: x64

init:
  - "C:\\MinGW\\bin\\gcc.exe -v"

install:
  - "SET PATH=%PATH%;C:\\MinGW\\bin"
  - "gcc -v"
  - "cd %APPVEYOR_BUILD_FOLDER%"
  - "gradlew installTestDebugExecutable"
  - "gradlew installTest_cppDebugExecutable"

test_script:
  - "cd  %APPVEYOR_BUILD_FOLDER%/build/install/test/debug/"
  - "test.bat"
  - "cd ../../test_cpp/debug"
  - "test_cpp.bat"
